"""Stable error codes shared with FE according to Self_Dev_Docs v2."""

from typing import Any


class DomainError(Exception):
    def __init__(self, code: str, message: str, status_code: int = 400, details: Any = None) -> None:
        super().__init__(message)
        self.code = code
        self.message = message
        self.status_code = status_code
        self.details = details


AUTH_REQUIRED = "AUTH_REQUIRED"
AUTH_TOKEN_MISSING = AUTH_REQUIRED
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_SERVICE_UNAVAILABLE = "AUTH_SERVICE_UNAVAILABLE"
AUTH_PROFILE_INVALID = "AUTH_PROFILE_INVALID"
USER_INACTIVE = "USER_INACTIVE"
FORBIDDEN = "FORBIDDEN"
UNIT_NOT_FOUND = "UNIT_NOT_FOUND"
ACCOUNT_ALREADY_BOUND = "ACCOUNT_ALREADY_BOUND"
UNIT_ALREADY_BOUND = "UNIT_ALREADY_BOUND"
NO_ACTIVE_UNIT = "NO_ACTIVE_UNIT"
TEXT_OR_IMAGE_REQUIRED = "TEXT_OR_IMAGE_REQUIRED"
DESCRIPTION_REQUIRED = "DESCRIPTION_REQUIRED"
IMAGE_UNREADABLE = "IMAGE_UNREADABLE"
INVALID_LOCATION = "INVALID_LOCATION"
TICKET_NOT_FOUND = "TICKET_NOT_FOUND"
TICKET_NOT_OWNED = "TICKET_NOT_OWNED"
TICKET_CREATE_RATE_LIMITED = "TICKET_CREATE_RATE_LIMITED"
INVALID_STATUS_TRANSITION = "INVALID_STATUS_TRANSITION"
AGENT_BUDGET_EXHAUSTED = "AGENT_BUDGET_EXHAUSTED"
P0_REVIEW_REQUIRED = "P0_REVIEW_REQUIRED"
CATEGORY_REQUIRED = "CATEGORY_REQUIRED"
SEVERITY_REQUIRED = "SEVERITY_REQUIRED"
OVERRIDE_REASON_REQUIRED = "OVERRIDE_REASON_REQUIRED"
CONFLICT_VERSION = "CONFLICT_VERSION"
ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND"
INVALID_ATTACHMENT = "INVALID_ATTACHMENT"
ASSIGNMENT_NOT_FOUND = "ASSIGNMENT_NOT_FOUND"
TECHNICIAN_NOT_FOUND = "TECHNICIAN_NOT_FOUND"
TECHNICIAN_NOT_ELIGIBLE = "TECHNICIAN_NOT_ELIGIBLE"
ACTIVE_ASSIGNMENT_EXISTS = "ACTIVE_ASSIGNMENT_EXISTS"
ASSIGNMENT_JOB_ALREADY_ACTIVE = "ASSIGNMENT_JOB_ALREADY_ACTIVE"
PROPOSAL_NOT_READY = "PROPOSAL_NOT_READY"
PROPOSAL_EXPIRED = "PROPOSAL_EXPIRED"
# 4.2: an empty batch carries nothing to assign, so confirming it can only
# mean "turn auto-assignment on for the tickets that come next".
PROPOSAL_NOTHING_TO_ASSIGN = "PROPOSAL_NOTHING_TO_ASSIGN"
# 4.1: the switch turns on through a confirmed proposal and nowhere else.
AUTO_ASSIGNMENT_PROPOSAL_REQUIRED = "AUTO_ASSIGNMENT_PROPOSAL_REQUIRED"
COMPLETION_EVIDENCE_REQUIRED = "COMPLETION_EVIDENCE_REQUIRED"
INFORMATION_REQUEST_NOT_FOUND = "INFORMATION_REQUEST_NOT_FOUND"
STORAGE_NOT_CONFIGURED = "STORAGE_NOT_CONFIGURED"
DATABASE_NOT_CONFIGURED = "DATABASE_NOT_CONFIGURED"
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_ERROR = "INTERNAL_ERROR"
