"use client";

import { ChevronLeft, Layers3, MoreHorizontal, X } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { approveCoordinatorCluster, assignCoordinatorCluster, listCoordinatorClusters, listCoordinatorTechnicians, removeCoordinatorClusterTicket } from "@/api/backend.api";
import { TicketDetailPanel } from "@/components/manager/TicketDetailPanel";
import { ManagerSurface } from "@/components/manager/ManagerSurface";
import { RoleShell } from "@/components/RoleShell";
import { PriorityBadge } from "@/components/StatusBadge";
import { formatCategoryName } from "@/lib/category";
import type { CoordinatorCluster, CoordinatorClusterTicket, TechnicianSummary } from "@/types/api";

export default function ManagerClustersPage() {
  const [clusters, setClusters] = useState<CoordinatorCluster[]>([]), [technicians, setTechnicians] = useState<TechnicianSummary[]>([]), [selectedClusterId, setSelectedClusterId] = useState<string | null>(null), [selectedTicketId, setSelectedTicketId] = useState<string | null>(null), [removing, setRemoving] = useState<CoordinatorClusterTicket | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("");
  const load = useCallback(async () => { try { setClusters(await listCoordinatorClusters()); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không tải được case."); } }, []);
  useEffect(() => { void load(); void listCoordinatorTechnicians().then(setTechnicians).catch(() => setTechnicians([])); }, [load]);
  const cluster = clusters.find((item) => item.id === selectedClusterId) || null;
  const remove = async () => { if (!cluster || !removing || busy) return; setBusy(true); setError(""); try { const next = await removeCoordinatorClusterTicket(cluster.id, removing.id); setClusters((items) => items.map((item) => item.id === next.id ? next : item)); setSelectedTicketId((value) => value === removing.id ? null : value); setRemoving(null); setNotice("Đã loại ticket khỏi cụm."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể loại ticket khỏi cụm."); } finally { setBusy(false); } };
  return <RoleShell role="manager" title="Cụm ticket" subtitle="Theo dõi các sự cố có khả năng liên quan."><div className="managerPageStack">
    <div className="managerInfoStrip"><Layers3 size={18} /><div><strong>Quy tắc gom cụm</strong><span>Các ticket cùng loại, ở cùng tầng hoặc tầng liền kề và phát sinh trong vòng 3 ngày có thể được gom thành một case. Mức độ lan rộng của case được dùng khi tính mức ưu tiên.</span></div></div>
    <div className={`ticketMasterDetail${selectedTicketId && cluster ? " detailOpen" : ""}`}><div className="ticketListColumn">
    {!cluster && error && <div className="alert error">{error}</div>}
    {!cluster && clusters.length > 0 && <ManagerSurface title="Case đang theo dõi" description="Mở case để xem và điều phối các ticket liên quan." icon={<Layers3 size={19} />} actions={<span className="managerCountBadge">{clusters.length} case</span>}>
      <section className="clusterGrid">{clusters.map((item) => <article className="clusterCard" key={item.id}><header><div><strong>Case #{item.id.slice(0, 8).toUpperCase()} · {formatCategoryName(item.category)}</strong><span>{item.floor_label}</span></div><div className="clusterHeaderBadges"><span className="badge managerTableStatus processing">{caseStatus(item)}</span></div></header><div className="clusterTickets clusterPreview">{item.tickets.slice(0, 3).map((ticket) => <div key={ticket.id}><strong>{formatCategoryName(item.category)}</strong><span>{ticket.location_label || ticket.floor_label || "Chưa xác định"}</span><small>{shortDate(ticket.created_at)}</small></div>)}{item.tickets.length > 3 && <span className="clusterMore">+{item.tickets.length - 3} ticket khác</span>}</div><button className="button secondary small clusterOpenButton" type="button" onClick={() => setSelectedClusterId(item.id)}>Mở case</button></article>)}</section>
    </ManagerSurface>}
    {cluster && <CaseDetail cluster={cluster} technicians={technicians} selectedTicketId={selectedTicketId} busy={busy} error={error} notice={notice} back={() => { setSelectedClusterId(null); setSelectedTicketId(null); }} openTicket={setSelectedTicketId} removeTicket={setRemoving} refresh={load} />}
    </div>{selectedTicketId && cluster && <TicketDetailPanel ticketId={selectedTicketId} caseInfo={`Case #${cluster.id.slice(0, 8).toUpperCase()} · ${formatCategoryName(cluster.category)}`} onClose={() => setSelectedTicketId(null)} onUpdated={() => void load()} />}</div>
    {removing && cluster && <RemoveModal ticket={removing} caseId={cluster.id} busy={busy} error={error} cancel={() => setRemoving(null)} confirm={() => void remove()} />}
  </div></RoleShell>;
}

function CaseDetail({ cluster, technicians, selectedTicketId, busy, error, notice, back, openTicket, removeTicket, refresh }: { cluster: CoordinatorCluster; technicians: TechnicianSummary[]; selectedTicketId: string | null; busy: boolean; error: string; notice: string; back: () => void; openTicket: (id: string) => void; removeTicket: (ticket: CoordinatorClusterTicket) => void; refresh: () => void }) {
  const [assigning, setAssigning] = useState(false); const canApprove = cluster.tickets.some((ticket) => ticket.status === "NEW"); const canAssign = cluster.tickets.some((ticket) => ticket.status === "APPROVED" && !ticket.active_assignment_id);
  const approve = async () => { try { await approveCoordinatorCluster(cluster.id); refresh(); } catch { /* request error appears through normal refresh */ } };
  const assign = async (id: string) => { try { await assignCoordinatorCluster(cluster.id, id); setAssigning(false); refresh(); } catch { /* request error appears through normal refresh */ } };
  return <><ManagerSurface className="clusterDetailSurface" title={`Case #${cluster.id.slice(0, 8).toUpperCase()} · ${formatCategoryName(cluster.category)}`} description={cluster.floor_label} icon={<Layers3 size={19} />} actions={<button className="iconButton clusterBackButton" type="button" onClick={back} title="Quay lại danh sách case" aria-label="Quay lại danh sách case"><ChevronLeft size={18} /></button>}>
    {notice && <div className="alert success">{notice}</div>}{error && <div className="alert error">{error}</div>}<div className="clusterDetailBadges"><span className="badge managerTableStatus processing">{caseStatus(cluster)}</span></div><section className="clusterStatRow"><div><strong>{cluster.tickets.length}</strong><span>Ticket trong case</span></div><div><strong>{highestPriority(cluster.tickets)}</strong><span>Ưu tiên cao nhất</span></div><div><strong>{caseStatus(cluster)}</strong><span>Trạng thái case</span></div></section><div className="clusterDetailListLabel">Danh sách ticket ({cluster.tickets.length})</div><section className="clusterDetailTickets">{cluster.tickets.map((ticket) => <article className={`clusterDetailTicket${selectedTicketId === ticket.id ? " selected" : ""}`} role="button" tabIndex={0} onClick={() => openTicket(ticket.id)} onKeyDown={(event) => { if (event.key === "Enter") openTicket(ticket.id); }} key={ticket.id}><header><div><strong>{ticket.display_code}</strong><span>{formatCategoryName(cluster.category)} · {ticket.location_label || ticket.floor_label || "Chưa xác định"}</span></div><div>{ticket.priority && <PriorityBadge priority={ticket.priority} />}<button className="iconButton clusterOverflow" title="Loại khỏi cụm" aria-label={`Loại ${ticket.display_code} khỏi cụm`} onClick={(event) => { event.stopPropagation(); removeTicket(ticket); }}><MoreHorizontal size={18} /></button></div></header><p>{ticket.description || "Không có mô tả."}</p><footer><span>{`Gửi lúc ${shortDate(ticket.created_at)}`}</span><span>{ticket.active_assignment_id ? `KTV: ${ticket.active_technician_name || "Kỹ thuật viên"}` : "Chưa có KTV"}</span></footer></article>)}</section>{(canApprove || canAssign) && <div className="clusterCaseActionbar">{canApprove && <button className="button secondary" disabled={busy} onClick={() => void approve()}>Duyệt cả cụm</button>}{canAssign && <button className="button" disabled={busy} onClick={() => setAssigning(true)}>Gán kỹ thuật viên</button>}</div>}
  </ManagerSurface>{assigning && <AssignModal technicians={technicians} busy={busy} close={() => setAssigning(false)} submit={assign} />}</>;
}
function RemoveModal({ ticket, caseId, busy, error, cancel, confirm }: { ticket: CoordinatorClusterTicket; caseId: string; busy: boolean; error: string; cancel: () => void; confirm: () => void }) { return <div className="modalBackdrop"><section className="managerModal"><header><strong>Loại ticket khỏi cụm?</strong><button className="iconButton" onClick={cancel} aria-label="Đóng"><X size={17} /></button></header><div className="managerModalBody"><p>Ticket {ticket.display_code} sẽ không còn thuộc Case #{caseId.slice(0, 8).toUpperCase()}. Ticket vẫn được giữ trong hệ thống và không bị xóa.</p>{error && <div className="alert error">{error}</div>}<div className="modalActions"><button className="button secondary" disabled={busy} onClick={cancel}>Hủy</button><button className="button destructive" disabled={busy} onClick={confirm}>{busy ? "Đang loại..." : "Loại khỏi cụm"}</button></div></div></section></div>; }
function AssignModal({ technicians, busy, close, submit }: { technicians: TechnicianSummary[]; busy: boolean; close: () => void; submit: (id: string) => void }) { const [id, setId] = useState(technicians.find((row) => row.is_available)?.user_id || ""); return <div className="modalBackdrop"><section className="managerModal"><header><strong>Gán kỹ thuật viên</strong><button className="iconButton" onClick={close}><X size={17} /></button></header><div className="managerModalBody"><select value={id} onChange={(event) => setId(event.target.value)}><option value="">Chọn kỹ thuật viên</option>{technicians.filter((row) => row.is_available).map((row) => <option value={row.user_id} key={row.user_id}>{row.full_name || row.user_id}</option>)}</select><div className="modalActions"><button className="button secondary" onClick={close}>Hủy</button><button className="button" disabled={!id || busy} onClick={() => submit(id)}>Gán</button></div></div></section></div>; }
function highestPriority(tickets: CoordinatorClusterTicket[]) { return tickets.some((ticket) => ticket.priority === "P3") ? "P3" : tickets.some((ticket) => ticket.priority === "P2") ? "P2" : tickets.some((ticket) => ticket.priority === "P1") ? "P1" : "—"; }
function caseStatus(cluster: CoordinatorCluster) { return cluster.closed ? "Hoàn thành" : "Đang theo dõi"; }
function shortDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "Chưa xác định" : new Intl.DateTimeFormat("vi-VN", { hour: "2-digit", minute: "2-digit", day: "2-digit", month: "2-digit" }).format(date); }
